<?php

declare(strict_types=1);

namespace Drupal\Tests\Core\Async\Fixtures;

/**
 * A service whose proxy is only ever generated by the class loader test.
 */
class FiberLocalLoaderFixture implements FiberLocalCounterInterface {

  /**
   * The count.
   */
  protected int $count = 0;

  /**
   * {@inheritdoc}
   */
  public function increment(int $by = 1): int {
    return $this->count += $by;
  }

  /**
   * {@inheritdoc}
   */
  public function get(): int {
    return $this->count;
  }

  /**
   * {@inheritdoc}
   */
  public function log(): array {
    return [];
  }

}
